# Cohesion configuration files.
- config/dx8/cohesion_component_category_cpt_cat_template_components_template-components.package.yml_
- config/dx8/cohesion_component_template_footer_template-footer.package.yml_
- config/dx8/cohesion_menu_templates_footer_menu_template_footer.package.yml_
- config/dx8/cohesion_component_cpt_template_header_template-header.package.yml_
- config/dx8/cohesion_menu_templates_menu_template_main_navigation_main-navigation.package.yml_
- config/dx8/cohesion_master_templates_master_template_master-template.package.yml
- config/dx8/cohesion_master_templates_master_template_boxed_master-template-boxed.package.yml
