- config/dx8/cohesion_component_category_cpt_cat_template_components_template-components.package.yml
- config/dx8/cohesion_component_template_footer_template-footer.package.yml
- config/dx8/cohesion_menu_templates_footer_menu_template_footer.package.yml
