# Cohesion configuration - Colors
- config/dx8/uswds_colors.package.yml_

# Cohesion configuration - Fonts
- config/dx8/uswds_fonts.package.yml_

# Cohesion configuration - Style Helpers
- config/dx8/uswds_style_helpers.package.yml_

# Cohesion configuration - Base styles
- config/dx8/uswds_base_styles.package.yml_
- config/dx8/base_style_teaser_view_content_border.package.yml_

# Cohesion configuration - Custom styles
- config/dx8/custom_style_accordion.package.yml_
- config/dx8/custom_style_button_cta_cyan.package.yml_
- config/dx8/custom_style_button_cta.package.yml_
- config/dx8/custom_style_button_solid.package.yml_
- config/dx8/custom_style_card_person.package.yml_
- config/dx8/custom_style_contact_info_block.package.yml_
- config/dx8/custom_style_container_theme_gray_5.package.yml_
- config/dx8/custom_style_dark_tab_active.package.yml_
- config/dx8/custom_style_dark_tab.package.yml_
- config/dx8/custom_style_heading_1_size_medium.package.yml_
- config/dx8/custom_style_heading_1_size.package.yml_
- config/dx8/custom_style_heading_2_size.package.yml_
- config/dx8/custom_style_link_button.package.yml_
- config/dx8/custom_style_link_with_icon.package.yml_
- config/dx8/custom_style_margin_left_large.package.yml_
- config/dx8/custom_style_max_width_accordion_wide.package.yml_
- config/dx8/custom_style_search_block.package.yml_
- config/dx8/custom_style_slider_navigation_left.package.yml_
- config/dx8/custom_style_slider_pagination.package.yml_
- config/dx8/custom_style_tab.package.yml_
- config/dx8/custom_style_pre_heading.package.yml_

# Cohesion configuration - Components
- config/dx8/component_accordion_container.package.yml_
- config/dx8/component_card_vertical.package.yml_
- config/dx8/component_contact_information.package.yml_
- config/dx8/component_footer.package.yml_
- config/dx8/component_header.package.yml_
- config/dx8/component_hero_left_aligned_text_with_background_image.package.yml_
- config/dx8/component_tabs_container_horizontal_tabs.package.yml_
- config/dx8/component_webform_block.package.yml_

# Cohesion configuration - Content Templates
- config/dx8/node_article_card.package.yml_
- config/dx8/node_article_full.package.yml_
- config/dx8/node_article_horizontal_card.package.yml_
- config/dx8/node_event_card.package.yml_
- config/dx8/node_event_full.package.yml_
- config/dx8/node_event_horizontal_card.package.yml_
- config/dx8/node_page_full.package.yml_
- config/dx8/node_person_card.package.yml_
- config/dx8/node_person_full.package.yml_
- config/dx8/node_place_card.package.yml_
- config/dx8/node_place_places.package.yml_

# Cohesion configuration - View Templates
- config/dx8/search_view.package.yml_
- config/dx8/articles_listing_view_fallback.package.yml_
- config/dx8/articles_listing_view.package.yml_
- config/dx8/events_listing_view_fallback.package.yml_
- config/dx8/events_listing_view_with_featured.package.yml_
- config/dx8/events_listing_view.package.yml_
- config/dx8/people_listing_view_fallback.package.yml_
- config/dx8/people_listing_view.package.yml_
- config/dx8/places_listing_view_fallback.package.yml_
- config/dx8/places_listing_view.package.yml_
- config/dx8/recent_articles_with_featured_view.package.yml_

# Cohesion configuration - Menu Templates
- config/dx8/menu.footer.package.yml_
- config/dx8/menu.main_navigation.package.yml_
- config/dx8/menu.uswds.footer.package.yml_
- config/dx8/menu.uswds.main_navigation.package.yml_
