# Cohesion configuration files.
- config/dx8/cards.package.yml_
- config/dx8/colors.package.yml_
- config/dx8/project_card.package.yml_
- config/dx8/cohesion_component_background-container.package.yml_
- config/dx8/map.package.yml_
- config/dx8/accordion.package.yml_
- config/dx8/button.package.yml_
- config/dx8/cohesion_component_ae486950_tab_item.package.yml_
- config/dx8/cohesion_component_80ee26fb_tabs_container_horizontal_tabs.package.yml_
- config/dx8/cohesion_component_contact_information.package.yml_
- config/dx8/cohesion_component_cpt_sidebar_nav_template-sidebar-nav.package.yml_
- config/dx8/cohesion_component_cpt_column.package.yml_
- config/dx8/cohesion_custom_style_181bb73d_light_tab_active.package.yml_
- config/dx8/cohesion_custom_style_d0fbb01f_dark_tab_active.package.yml_
- config/dx8/cohesion_custom_style_cbec2ae7_light_tab.package.yml_
- config/dx8/cohesion_custom_style_579db8e2_dark_tab.package.yml_
- config/dx8/cohesion_custom_style_padding-left-right-extra-small.package.yml_
- config/dx8/cohesion_custom_style_date-with-ribbon.package.yml_
- config/dx8/cohesion_custom_style_sidebar-nav.package.yml_
- config/dx8/slider.package.yml_
- config/dx8/hero.package.yml_
- config/dx8/cohesion_base_styles_(unordered_list)_unordered-list.package.yml_
- config/dx8/cohesion_base_styles_(base_form)_form.package.yml_
- config/dx8/cohesion_component_cpt_template_header_template-header.package.yml_
- config/dx8/cohesion_component_text.package.yml_
- config/dx8/background_image_hero.package.yml_
- config/dx8/cohesion_menu_templates_menu_tpl_side_nav_side-nav.package.yml_
- config/dx8/two_column_page_hero.package.yml_
- config/dx8/cohesion_custom_style_pager-alignment.package.yml_
- config/dx8/cohesion_custom_style_(19a14825)_padding-medium.package.yml_
- config/dx8/cohesion_custom_style_(2300d6b4)_padding-large.package.yml_
- config/dx8/cohesion_component_cpt_drupal_blocks.package.yml_
- config/dx8/cohesion_custom_style_(e2a1a6d7)_margin-bottom-x-small.package.yml_
- config/dx8/cohesion_custom_style_breadcrumb-block.package.yml_
- config/dx8/cohesion_custom_style_(fff38366)_card-person.package.yml_
- config/dx8/cohesion_custom_style_rounded_card_image_wrapper.package.yml_
