# Cohesion configuration - Colors
- config/dx8/colors.package.yml_

# Cohesion configuration - Base Styles
- config/dx8/base_style_link.package.yml_
- config/dx8/base_style_body.package.yml_
- config/dx8/base_style_form.package.yml_
- config/dx8/base_style_unordered_list.package.yml_
- config/dx8/base_style_visually_hidden.package.yml_

# Cohesion configuration - Custom Styles
- config/dx8/custom_style_accordion_border.package.yml_
- config/dx8/custom_style_accordion.package.yml_
- config/dx8/custom_style_breadcrumb_block.package.yml_
- config/dx8/custom_style_button_cta.package.yml_
- config/dx8/custom_style_button_outline.package.yml_
- config/dx8/custom_style_button_solid.package.yml_
- config/dx8/custom_style_button_unstyled.package.yml_
- config/dx8/custom_style_card_person.package.yml_
- config/dx8/custom_style_clear_facets_block.package.yml_
- config/dx8/custom_style_dark_tab_active.package.yml_
- config/dx8/custom_style_dark_tab.package.yml_
- config/dx8/custom_style_date_with_ribbon.package.yml_
- config/dx8/custom_style_height_variable.package.yml_
- config/dx8/custom_style_light_tab_active.package.yml_
- config/dx8/custom_style_light_tab.package.yml_
- config/dx8/custom_style_link_button.package.yml_
- config/dx8/custom_style_link_button_dark.package.yml_
- config/dx8/custom_style_link_button_light.package.yml_
- config/dx8/custom_style_margin_bottom_x_small.package.yml_
- config/dx8/custom_style_margin_left_large.package.yml_
- config/dx8/custom_style_margin_left_medium.package.yml_
- config/dx8/custom_style_margin_left_small.package.yml_
- config/dx8/custom_style_margin_right_large.package.yml_
- config/dx8/custom_style_margin_right_medium.package.yml_
- config/dx8/custom_style_margin_right_small.package.yml_
- config/dx8/custom_style_padding_large.package.yml_
- config/dx8/custom_style_padding_left_right_extra_small.package.yml_
- config/dx8/custom_style_padding_medium.package.yml_
- config/dx8/custom_style_padding_left_large.package.yml_
- config/dx8/custom_style_padding_left_medium.package.yml_
- config/dx8/custom_style_padding_left_small.package.yml_
- config/dx8/custom_style_padding_right_large.package.yml_
- config/dx8/custom_style_padding_right_medium.package.yml_
- config/dx8/custom_style_padding_right_small.package.yml_
- config/dx8/custom_style_padding_top_bottom_extra_small.package.yml_
- config/dx8/custom_style_pager_alignment.package.yml_
- config/dx8/custom_style_position_left.package.yml_
- config/dx8/custom_style_rounded_card_image_wrapper.package.yml_
- config/dx8/custom_style_row_column_padding_left_right_zero.package.yml_
- config/dx8/custom_style_search_block.package.yml_
- config/dx8/custom_style_sidebar_nav.package.yml_
- config/dx8/custom_style_slider_navigation_left.package.yml_
- config/dx8/custom_style_slider_navigation_right.package.yml_
- config/dx8/custom_style_tab.package.yml_

# Cohesion configuration - Components Category
- config/dx8/category_general_components.package.yml_
- config/dx8/category_hero_components.package.yml_
- config/dx8/category_layout_components.package.yml_
- config/dx8/category_map_components.package.yml_

# Cohesion configuration - Components preview images
- config/dx8/file_preview_component_acordion_container.package.yml_
- config/dx8/file_preview_component_acordion_item.package.yml_
- config/dx8/file_preview_component_background_container.package.yml_
- config/dx8/file_preview_component_banner.package.yml_
- config/dx8/file_preview_component_breadcrumb.package.yml_
- config/dx8/file_preview_component_button.package.yml_
- config/dx8/file_preview_component_button_container.package.yml_
- config/dx8/file_preview_component_card_container.package.yml_
- config/dx8/file_preview_component_card_entity_reference.package.yml_
- config/dx8/file_preview_component_card_horizontal.package.yml_
- config/dx8/file_preview_component_card_horizontal_16_9.package.yml_
- config/dx8/file_preview_component_card_image.package.yml_
- config/dx8/file_preview_component_card_project.package.yml_
- config/dx8/file_preview_component_card_vertical.package.yml_
- config/dx8/file_preview_component_card_video.package.yml_
- config/dx8/file_preview_component_column.package.yml_
- config/dx8/file_preview_component_contact_information.package.yml_
- config/dx8/file_preview_component_drupal_blocks.package.yml_
- config/dx8/file_preview_component_footer.package.yml_
- config/dx8/file_preview_component_google_map.package.yml_
- config/dx8/file_preview_component_google_map_marker.package.yml_
- config/dx8/file_preview_component_header.package.yml_
- config/dx8/file_preview_component_hero.package.yml_
- config/dx8/file_preview_component_row.package.yml_
- config/dx8/file_preview_component_sidebar_nav.package.yml_
- config/dx8/file_preview_component_slide_container.package.yml_
- config/dx8/file_preview_component_slide_item.package.yml_
- config/dx8/file_preview_component_tab_item.package.yml_
- config/dx8/file_preview_component_tabs_container.package.yml_
- config/dx8/file_preview_component_text.package.yml_
- config/dx8/file_preview_component_title.package.yml_
- config/dx8/file_preview_component_two_column.package.yml_
- config/dx8/file_preview_helper_image_background_hero.package.yml_
- config/dx8/file_preview_helper_two_column_page_with_hero.package.yml_

# Cohesion configuration - Helpers preview images
- config/dx8/helper_image_background_hero.package.yml_
- config/dx8/helper_two_column_page_with_hero.package.yml_

# Cohesion configuration - Components
- config/dx8/component_accordion_container.package.yml_
- config/dx8/component_accordion_item.package.yml_
- config/dx8/component_background_container.package.yml_
- config/dx8/component_banner.package.yml_
- config/dx8/component_breadcrumb.package.yml_
- config/dx8/component_button_container.package.yml_
- config/dx8/component_button.package.yml_
- config/dx8/component_card_container.package.yml_
- config/dx8/component_card_entity_reference.package.yml_
- config/dx8/component_card_horizontal_16_9.package.yml_
- config/dx8/component_card_horizontal_portrait.package.yml_
- config/dx8/component_card_image.package.yml_
- config/dx8/component_card_project.package.yml_
- config/dx8/component_card_vertical.package.yml_
- config/dx8/component_card_video.package.yml_
- config/dx8/component_column.package.yml_
- config/dx8/component_contact_information.package.yml_
- config/dx8/component_drupal_blocks.package.yml_
- config/dx8/component_footer.package.yml_
- config/dx8/component_google_map_marker.package.yml_
- config/dx8/component_google_map.package.yml_
- config/dx8/component_header.package.yml_
- config/dx8/component_hero.package.yml_
- config/dx8/component_row.package.yml_
- config/dx8/component_sidebar_nav.package.yml_
- config/dx8/component_slide_container.package.yml_
- config/dx8/component_slide_item.package.yml_
- config/dx8/component_tab_item.package.yml_
- config/dx8/component_tabs_container_horizontal_tabs.package.yml_
- config/dx8/component_text.package.yml_
- config/dx8/component_title.package.yml_
- config/dx8/component_two_column.package.yml_

# Cohesion configuration - Helpers
- config/dx8/helper_image_background_hero.package.yml_
- config/dx8/helper_two_column_page_with_hero.package.yml_

# Cohesion configuration - Menu Templates
- config/dx8/menu.footer.package.yml_
- config/dx8/menu.main_navigation.package.yml_
- config/dx8/menu.side_nav.package.yml_
