# Cohesion configuration files.
- config/dx8/cards.package.yml_
- config/dx8/project_card.package.yml_
- config/dx8/cohesion_component_background-image-container.package.yml
- config/dx8/map.package.yml_
- config/dx8/accordion.package.yml_
- config/dx8/button.package.yml_
- config/dx8/cohesion_component_ae486950_tab_item.package.yml_
- config/dx8/cohesion_component_80ee26fb_tabs_container_horizontal_tabs.package.yml_
- config/dx8/cohesion_component_contact_information.package.yml_
- config/dx8/cohesion_custom_style_181bb73d_light_tab_active.package.yml_
- config/dx8/cohesion_custom_style_d0fbb01f_dark_tab_active.package.yml_
- config/dx8/cohesion_custom_style_cbec2ae7_light_tab.package.yml_
- config/dx8/cohesion_custom_style_579db8e2_dark_tab.package.yml_
- config/dx8/cohesion_custom_style_padding-left-right-extra-small.package.yml_
- config/dx8/cohesion_custom_style_date-with-ribbon.package.yml_
- config/dx8/slider.package.yml_
- config/dx8/hero.package.yml_
- config/dx8/cohesion_base_styles_(unordered_list)_unordered-list.package.yml_
- config/dx8/cohesion_custom_style_(ce793494)_form.package.yml_
