-
  type: default_module_package
  source:
    module_name: acquia_cms_site_studio
    path: config/pack_acquia_cms_core
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_video
    path: config/pack_acquia_cms_video
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_search
    path: config/pack_acquia_cms_search
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_image
    path: config/pack_acquia_cms_image
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_image
    path: config/pack_acquia_cms_core_image
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_page
    path: config/pack_acquia_cms_page
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_place
    path: config/pack_acquia_cms_place
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_event
    path: config/pack_acquia_cms_event
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_person
    path: config/pack_acquia_cms_person
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_article
    path: config/pack_acquia_cms_article
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_dam
    path: config/pack_acquia_cms_dam
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    required: FALSE
    module_name: acquia_cms_audio
    path: config/pack_acquia_cms_audio
  options:
    extra-validation: false
