- /config/dx8/cohesion_view_templates.view_tpl_articles.yml_
- /config/dx8/cohesion_view_templates.view_tpl_articles_fallback.yml_
- /config/dx8/cohesion_view_templates.view_tpl_articles_grid.yml_
- /config/dx8/cohesion_content_templates.node_article_card.yml_
- /config/dx8/cohesion_content_templates.node_article_full.yml_
- /config/dx8/cohesion_content_templates.node_article_horizontal_card.yml_
- /config/dx8/cohesion_content_templates.node_article_search_results.yml_
- /config/dx8/cohesion_content_templates.node_article_teaser.yml_
- /config/dx8/cohesion_view_templates.view_tpl_article_cards_slider.yml_
