- /config/dx8/cohesion_content_templates.node_place_card.yml_
- /config/dx8/cohesion_content_templates.node_place_full.yml_
- /config/dx8/cohesion_content_templates.node_place_horizontal_card.yml_
- /config/dx8/cohesion_content_templates.node_place_search_results.yml_
- /config/dx8/cohesion_content_templates.node_place_teaser.yml_
- /config/dx8/cohesion_view_templates.view_tpl_places.yml_
- /config/dx8/cohesion_view_templates.view_tpl_places_fallback.yml_
- /config/dx8/cohesion_view_templates.view_tpl_places_grid.yml_
