# Cohesion content template configuration files for place content type.
- config/dx8/cohesion_content_templates_node_place_full_full-content-node-place-.package.yml_
- config/dx8/cohesion_content_templates_node_place_teaser_teaser-node-place-.package.yml_
- config/dx8/cohesion_content_templates_node_place_card_card-node-place-.package.yml_
