- /config/dx8/cohesion_content_templates.node_person_card.yml_
- /config/dx8/cohesion_content_templates.node_person_full.yml_
- /config/dx8/cohesion_content_templates.node_person_horizontal_card.yml_
- /config/dx8/cohesion_content_templates.node_person_search_results.yml_
- /config/dx8/cohesion_content_templates.node_person_teaser.yml_
- /config/dx8/cohesion_view_templates.view_tpl_people.yml_
- /config/dx8/cohesion_view_templates.view_tpl_people_grid.yml_
- /config/dx8/cohesion_view_templates.view_tpl_people_fallback.yml_
