# Cohesion configuration - Custom Styles
- config/dx8/custom_style_link_with_location_icon.package.yml_

# Cohesion configuration - Content Templates
- config/dx8/node_event_card.package.yml_
- config/dx8/node_event_full.package.yml_
- config/dx8/node_event_horizontal_card.package.yml_
- config/dx8/node_event_teaser.package.yml_
- config/dx8/node_event_search_results.yml_

# Cohesion configuration - View Templates
- config/dx8/events_listing_view_fallback.package.yml_
- config/dx8/events_listing_view_with_featured.package.yml_
- config/dx8/events_listing_view.package.yml_
