- /config/dx8/cohesion_content_templates.media_image_embedded.yml_
- /config/dx8/cohesion_content_templates.media_video_embedded.yml_
- /config/dx8/cohesion_content_templates.media_video_full.yml_
- /config/dx8/cohesion_content_templates.media_video_video_component.yml_
