- /config/dx8/cohesion_content_templates.node_page_card.yml_
- /config/dx8/cohesion_content_templates.node_page_full.yml_
- /config/dx8/cohesion_content_templates.node_page_horizontal_card.yml_
- /config/dx8/cohesion_content_templates.node_page_search_results.yml_
- /config/dx8/cohesion_content_templates.node_page_teaser.yml_
