# Cohesion configuration files.
- config/dx8/node_page_card.package.yml_
- config/dx8/node_page_full.package.yml_
- config/dx8/node_page_horizontal_card.package.yml_
- config/dx8/node_page_teaser.package.yml_
