name: 'Site Studio Configuration Management'
package: 'Acquia CMS'
description: 'Provides Site Studio recommended configuration management using config filter, config ignore & config split module.'
core_version_requirement: ^9 || ^10
type: module
dependencies:
  - config_filter:config_filter
  - config_ignore:config_ignore
  - config_split:config_split
  - cohesion_sync # phpcs:ignore
